### ISSUE TITLE
Removing controller.isDirty default logic

### ISSUE THREAD

**Issue by blimmer** [jasonmit/ember-onbeforeunload#10]
To be good Ember community members, we should discourage the use of `Ember.Controller`.

It would be a breaking change, but perhaps we should guide users to provide their own `canUnload` or have logic that utilizes `this.modelFor(this.routeName)` instead.

**Comment by jasonmit** [comment]
Was reading on my phone, didn't mean to close :). Is your concern that controllers are going away?

**Comment by blimmer** [comment]
Yep!

**Comment by jasonmit** [comment]
I'm down to move this responsibility to the route, unless you have some other ideas.

**Comment by blimmer** [comment]
Sounds great - I'll update the title.
