### ISSUE TITLE
Ember 3.6+ Support

### ISSUE THREAD

**Issue by aaronfischer** [jasonmit/ember-onbeforeunload#19]
Hello! 
Are there any current plans to get this upgraded to 3.6+? With the eventual deprecation of `willTransition` and `didTransition`. I may try taking a look at this when I get a chance. Hopefully just moving this into the `init()` and going off the new router events. https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_transition-state

**Comment by blimmer** [comment]
Hey @Aaronfischer - thanks for reaching out. I'm not working in Ember that much these days so this isn't on my radar at the moment. If you're willing to open a PR, that'd be great!

Looking at the link, it looks like they're going to keep these hooks until 4.0.0+, so we probably have some time and you'll want to make sure you don't break existing folks in the upgrade.
